Algoritmo "calculodeidade"
// 
//  
// Descrição   : calcula sua idade
// Autor(a)    : Thiago Nunes Miziara
// Data atual  : 21/7/2020
Var
   ano_atual, ano_nasc,idade:inteiro



Inicio
      escreva("Em que ano nós estamos?")
      leia(ano_atual)
      escreva("Em que ano eu nasci")
      leia(ano_nasc)
      idade<-ano_atual-ano_nasc
      escreva("Minha idade é  ",idade)
Fimalgoritmo
