Algoritmo "Nome e salario do funcionario"
// 
//  
// Descrição   : Aparece o nome e o salario do funcionario
// Autor(a)    : Thiago Nunes Miziara
// Data atual  : 18/7/2020
Var
nome:caracter
salario:real


Inicio
Escreva("Nome do funcionario:")
Leia(nome)
Escreva("Salario: ")
Leia(salario)
escreval("O funcionario ",nome," tem um salario de R$",salario," em Junho")

Fimalgoritmo