Algoritmo "Quantos dólares posso comprar"
//  
//  
// 
//  
// Descrição   : converter o real em dolar(usando o valor do dolar da data da criaçao)
// Autor(a)    : Thiago Nunes Miziara
// Data atual  : 22/7/2020
Var
   dolar,reais:real


Inicio
      Escreva("Quantos R$ tenho na carteira")
      leia(reais)
      dolar<-reais/5.11
      escreva("Com R$",reais," posso comprar US$",dolar)
Fimalgoritmo