Algoritmo "SomaFunção"
// 
//  
// Descrição   : soma 2 valores
// Autor(a)    : Thiago Nunes Miziara
// Data atual  : 26/7/2020
Var
   v1,v2,s:inteiro
Funcao soma(x,y:Inteiro):Inteiro
Inicio
   Retorne x+y

FimFuncao
Inicio
   Escreva("Digite o primeiro valor: ")
   Leia(v1)
   Escreva("Digite o segundo valor: ")
   Leia(v2)
   s<-soma(v1,v2)
   Escreva("A soma entrte ",v1," e ",v2," e igual a ",s)


Fimalgoritmo